moved docker group check target to docker utility make file

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -30,3 +30,11 @@ delete_all_build_cache:
 .PHONY: system_prune
 system_prune: ## Prune docker system
 	docker system prune --all --volumes --force
+
+.PHONY: docker_group_check
+docker_group_check:# Checks if the current user is a member of the 'docker' group. 
+	@[ -n "$$(id -Gn | grep 'docker')" ] || ( \
+         echo "  ERROR: User: '$$USER' is not a member of the 'docker' group."; 1>&2 \
+         echo "    Run 'sudo usermod -a -G docker \$$USER' to add the current user to the docker group and try again."; 1>&2 \
+         echo "    You may need to log out and log back in for changes to take effect." 1>&2 && exit 1 \
+    )
